version: '3.8'

services:
  db:
    image: mariadb:10.11.9
    container_name: next-video-conference-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@55w0rd
      MYSQL_DATABASE: videoconference
      MYSQL_USER: reyshal
      MYSQL_PASSWORD: p@55w0rd
    ports:
      - "3308:3306"
    volumes:
      - ./docker_mysql_init.sql:/docker-entrypoint-initdb.d/docker_mysql_init.sql
      - app_db:/var/lib/mysql

  db_ui:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "16543:16543"

volumes:
  app_db: